// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7RQ8JTvhEShVCWnCuP98OQbIxJ8wz-1o',
    appId: '1:915877874882:web:1e2ec4a2967b5b0976ff5b',
    messagingSenderId: '915877874882',
    projectId: 'flutter-workflow-actions',
    authDomain: 'flutter-workflow-actions.firebaseapp.com',
    storageBucket: 'flutter-workflow-actions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2pYiP3w-00R_ums3LuAuAhf12qbAWCmQ',
    appId: '1:915877874882:android:de697fc904154f7176ff5b',
    messagingSenderId: '915877874882',
    projectId: 'flutter-workflow-actions',
    storageBucket: 'flutter-workflow-actions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsPKTHyWme8o8ZClHBouVMaagrV6Clu4',
    appId: '1:915877874882:ios:4c3363d2d139d06576ff5b',
    messagingSenderId: '915877874882',
    projectId: 'flutter-workflow-actions',
    storageBucket: 'flutter-workflow-actions.appspot.com',
    iosClientId: '915877874882-s4ku3rtbn597273q6horipcql4sgnh8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkflowDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsPKTHyWme8o8ZClHBouVMaagrV6Clu4',
    appId: '1:915877874882:ios:4c3363d2d139d06576ff5b',
    messagingSenderId: '915877874882',
    projectId: 'flutter-workflow-actions',
    storageBucket: 'flutter-workflow-actions.appspot.com',
    iosClientId: '915877874882-s4ku3rtbn597273q6horipcql4sgnh8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkflowDemo',
  );
}
