name: Flutter build (android)

on:
  push:
    branches: [ build-android ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: stable
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload apk
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  deploy:
    name: Deploy beta to Firebase
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '12.x'
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: apk-build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_SERVICES_JSON }}
          token: ${{secrets.FIREBASE_TOKEN}}
          group: testers
          file: app-release.apk