name: Flutter build (android)

on:
  push:
    branches: [ build-android ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: stable
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload apk
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/release