name: Flutter build and publish (ios)

on:
  push:
    branchs: [ build-ios ]

jobs:
  build:
    runs-on: macos-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}
      ENV_PROFILE: "Apple Develoment: maikelyordanalmaralesleyva@gmail.com"

    steps:
      - uses: actions/checkout@v3

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{secrets.P12_BASE64}}
          p12-password: ${{secrets.P12_PASSWORD}}
      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{secrets.PROVISIONING_PROFILE_BASE64}}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: stable

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release
      
      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release DEVELOPMENT_TEAM=YOUR_TEAM_ID -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=YOUR_UUID clean archive CODE_SIGN_IDENTITY=${{ENV_PROFILE}}

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: Publish Artifacts
        uses: actions/upload-artifact@master
        with:
          name: release-ios
          path: build-output/ios