name: CI

on:
  push:
    branches: [ main ]

jobs:
  web:
    build:
      name: Flutter build ( Web )
        runs-on: ubuntu-latest
          env:
            my_secret: ${{secrets.ACCESS_TOKEN}}
          
          steps:
            - uses: actions/checkout@v3
            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.3.10'
                channel: 'stable'

            - run: flutter clean
            - run: flutter pub get
            - run: flutter build web --release

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{secrets.ACCESS_TOKEN}}
                publish_dir: ./build/web

    
    name: Flutter build ( android )
      runs-on: ubuntu-latest
      env:
        my_secret: ${{secrets.ACCESS_TOKEN}}

      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with: 
            java-version: '12.x'
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.3.10'
            channel: stable
        
        - run: flutter clean
        - run: flutter pub get
        - run: flutter build apk --release

        - name: Upload apk
          uses: actions/upload-artifact@master
          with:
            name: apk-build
            path: build/app/outputs/apk/release